providers:
  validators:
    applitoolsValidator: Monitor.Providers.ApplitoolsValidator
    urlRedirectionValidator: Monitor.Providers.UrlRedirectionValidator
    ttlValidator: Monitor.Providers.ttlValidator
  notifyer:
    log4netNotifyer: Monitor.Providers.Log4netNotifyer
  siteDataProvider:
    excelFileSiteDataProvider: Monitor.Providers.excelFileSiteDataProvider
components-params:
  engine:
    threads: 3
    browser: chrome
    gridAddress: 
    headless: true
  applitoolsValidator:
    serverUrl:
    apiKey:
    appName:
    batchname: Configuredbatch
    viewportsize:
      width: 1000
      height: 650
  excelFileSiteDataProvider:
    datafile: SiteList.xlsx
    addColumns: ttl